version: '2.1'

services:
  todos-server:
    image: todos-server
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 5000:5000
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js